### ISSUE TITLE
no file in output

### ISSUE THREAD

**Issue by stsch83** [cmccambridge/ocrmypdf-auto#14]
i installed under omv 4 docker.
when i look into the log file i can see, that the test.pdf was ocr(ed) and moved to the output directory. but when i look into my output directory there is no file.

**Comment by DJGauthier** [comment]
got same problem and I active debug mode to find out that the output dir did not have similar permissions as input and over directories for ocr. 
chmod +777 /output resolved this issue.
@cmccambridge : can you please correct the container image? thanks.

**Comment by cmccambridge** [comment]
Hi @stsch83, @DJGauthier: apologies for missing this issue go by. I'm not familiar with OMV 4 and how it incorporates and configures Docker, but I can try and provide a few tips.

The `ocrmypdf-auto` container image does include an empty folder at `/output`, but if I understand Docker correctly, the content and permissions of a volume properly mounted to this path will override the container's content entirely, so we are tracking down a configuration problem on your system, rather than anything I can assist with from within the container.

Some things to check would be:
* Confirm that your container has a volume properly mounted at `/output`, e.g. by looking at the output of `docker inspect -f "{{ .Mounts }}" your-container-id`
* Verify the permissions of your mounted path _outside_ the container. This includes both access mask and owner/group.
* This container by default runs with UID and GID both set to 1000. You may override these settings to match the owner of your output path using the `USERMAP_UID` and `USERMAP_GID` environment variables when starting the container. (See the [readme] for details). In another "managed Docker" environment that I am familiar with called [Unraid], I set `USERMAP_UID=99` and `USERMAP_GID=100` to be compatible with Unraid's default file ownership structure. Perhaps OMV4 has a similar well-known UID or GID that you can provide?

Let me know if you continue to encounter issues.

[readme]: https://github.com/cmccambridge/ocrmypdf-auto/blob/master/README.md#environment-variables-and-global-configuration
[Unraid]: https://unraid.net

**Comment by cmccambridge** [comment]
Not having seen any updates in some time, I will close this issue out. Please reopen if you're still looking for help!
